Style/FrozenStringLiteralComment:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false  

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Layout/AlignHash:
  EnforcedColonStyle: table

Metrics/LineLength:
  Max: 180

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'db/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'  
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/*'  
Style/MixinUsage:
  Exclude:
    - 'bin/*'
Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'