Style/Documentation:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

Layout/AlignHash:
  EnforcedColonStyle: table

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']  

Style/MixinUsage:
  Exclude:
    - 'bin/*'
